zmq_setup:
  timeout: 1000

# motors

hip_pitch_1:
  control_mode: D4_impedance_ctrl
  pid:
    impedance: [500.0, 10.0, 1.0, 0.003, 0.95]

knee_pitch_1:
  control_mode: D4_impedance_ctrl
  pid:
    impedance: [500.0, 10.0, 1.0, 0.003, 0.95]
