zmq_setup:
  timeout: 1000

# motors

hip_pitch_1:
  control_mode: 3B_motor_pos_ctrl
  pid:
    position: [220.0 , 0.0 , 5.0]

knee_pitch_1:
  control_mode: 3B_motor_pos_ctrl
  pid:
    position: [220.0 , 0.0 , 5.0]
