# YAML config file associated with jump_generation.py script.

i_q_estimation:
  tanh_coeff: 20

problem:
  n_int: 99
  n_takeoff: 34
  n_touchdown: 79
  dt_lb: 0.005
  dt_ub: 0.1
  jnt_limit_margin: 0.02
  jnt_vel_limit_margin: 0.05

  weights: 
    scale_factor_costs_base: 100000 # scale factor for costs (other scalings are applied internally)
    
    weight_f_contact: 0.00001 # cost for penalizing contact forces
    weight_f_contact_diff: 0.00001 # cost for penalizing differences between successive f_contacts
    weight_q_p_ddot: 0.00001 # cost for penalizing joint accelerations (which are the input)
    weight_input_diff: 0.00001 # cost for penalizing differences between successive inputs
    weight_com_height: 1
    weight_hip_height: 0.0000000000000000000001
    weight_tip_clearance: 0.0000000000000000000001

  ref_weights:
    contact_force: 0.00001 # cost for penalizing contact forces
    small_q_p_ddot: 0.00001 # cost for penalizing joint accelerations (which are the input)
    weight_f_contact_diff: 0.00001 # cost for penalizing differences between successive f_contacts
    weight_input_diff: 0.00001 # cost for penalizing differences between successive inputs
    weight_com_height: 0.00001
    weight_hip_height: 0.0000000000000000000001
    weight_tip_clearance: 0.0000000000000000000001

    weight_res_sol_tracking: 0.00001

solver:
  ipopt_tol: 0.000001
  ipopt_maxiter: 1000
  ipopt_cnstr_viol_tol: 0.0000001
  ipopt_lin_solver: "ma57" 
  name: "ipopt"

transcription:
  name: "multiple_shooting"
  integrator_name: "RK4"

resampling:
  dt: 0.04

