# YAML config file associated with jump_generation.py script.

i_q_estimation:
  tanh_coeff: 20

problem:

  is_accel_formulation: true # whether to use acceleration based formulation of torque-based formulation

  n_int: 99
  n_takeoff: 34
  n_touchdown: 79
  dt_lb: 0.005
  dt_ub: 0.1
  jnt_limit_margin: 0.02
  jnt_vel_limit_margin: 0.05

  is_iq_cnstrnt: false
  is_friction_cone: true

  friction_cnstrnt: 
    mu_friction_cone: 0.2

  use_same_weights: true

  weights: 

    scale_factor_costs_base: 100000 # scale factor for costs (other scalings are applied internally)
    
    weight_f_contact: 0.0001 # cost for penalizing contact forces
    weight_f_contact_diff: 0.001 # cost for penalizing differences between successive f_contacts
    weight_q_p_dot: 0.0001
    weight_q_p_ddot: 0.0001 # cost for penalizing joint accelerations (which are the input)
    weight_q_p_ddot_diff: 0.001 # cost for penalizing differences between successive inputs

    weight_com_height: 10
    weight_hip_height: 0.0000000000000000000001
    weight_tip_clearance: 0.0000000000000000000001
    weight_tip_under_hip: 200

  ref_weights:

    scale_factor_costs_base: 100000 # scale factor for costs (other scalings are applied internally)
    
    weight_f_contact: 0.0001 # cost for penalizing contact forces
    weight_f_contact_diff: 0.001 # cost for penalizing differences between successive f_contacts
    weight_q_p_dot: 0.0001
    weight_q_p_ddot: 0.0001 # cost for penalizing joint accelerations (which are the input)
    weight_q_p_ddot_diff: 0.001 # cost for penalizing differences between successive inputs

    weight_com_height: 50
    weight_hip_height: 0.0000000000000000000001
    weight_tip_clearance: 0.0000000000000000000001
    weight_tip_under_hip: 100

    weight_res_sol_tracking: 100

solver:
  ipopt_tol: 0.000001
  ipopt_maxiter: 1000
  ipopt_cnstr_viol_tol: 0.0000001
  ipopt_lin_solver: "mumps" 
  name: "ipopt"

transcription:
  name: "multiple_shooting"
  integrator_name: "RK4"

resampling:
  dt: 0.004

