# Config file associated with horizon_jump_replayer.py

horizon:
  horizon_replayer:
    urdf_name: awesome_leg_complete.urdf # urdf relative path (wrt to the package)
    # opt_results_rel_path: media/horizon_jump/29-05-2022/jump_test/jump_height_L1/horizon_offline_solver_res_12_30_48.mat # where optimization .mat
    # opt_results_rel_path: media/horizon_jump/29-05-2022/jump_test/jump_height_L2/horizon_offline_solver_res_12_31_34.mat # where optimization .mat
    # opt_results_rel_path: media/horizon_jump/29-05-2022/jump_test/jump_height_L3/horizon_offline_solver_res_12_32_14.mat # where optimization .mat
    # opt_results_rel_path: media/horizon_jump/29-05-2022/jump_test/jump_height_L4/horizon_offline_solver_res_12_32_46.mat # where optimization .mat
    opt_results_rel_path: media/horizon_jump/29-05-2022/jump_test/jump_height_L5/horizon_offline_solver_res_12_33_25.mat # where optimization .mat
