# Config file associated with horizon_jump_replayer.py

horizon:
  horizon_replayer:
    urdf_name: awesome_leg_complete.urdf # urdf relative path (wrt to the package)
    # opt_results_rel_path: media/horizon_jump/29-05-2022/jump_test/jump_height_L1/horizon_offline_solver_res_10_40_31.mat # where optimization .mat
    # opt_results_rel_path: media/horizon_jump/29-05-2022/jump_test/jump_height_L2/horizon_offline_solver_res_10_45_42.mat # where optimization .mat
    # opt_results_rel_path: media/horizon_jump/29-05-2022/jump_test/jump_height_L3/horizon_offline_solver_res_10_46_30.mat # where optimization .mat
    # opt_results_rel_path: media/horizon_jump/29-05-2022/jump_test/jump_height_L4/horizon_offline_solver_res_10_48_28.mat # where optimization .mat
    opt_results_rel_path: media/horizon_jump/29-05-2022/jump_test/jump_height_L5/horizon_offline_solver_res_10_49_08.mat # where optimization .mat
