# XBot2 Awesome Leg configuration file. To be used during testing.

# description
XBotInterface:
  urdf_path: $(rospack find awesome_leg)/description/urdf/generated/awesome_leg_xbot.urdf
  srdf_path: $(rospack find awesome_leg)/description/srdf/awesome_leg.srdf

# model interface
ModelInterface:
  model_type: RBDL
  is_model_floating_base: false

# hal
xbotcore_device_configs:
    sim: $PWD/../ecat_config/hal/awesome_leg_gz.yaml
    dummy: $PWD/../ecat_config/hal/awesome_leg_dummy.yaml
    ec_pos: $PWD/../ecat_config/hal/awesome_leg_ec_all.yaml
    ec_imp: $PWD/../ecat_config/hal/awesome_leg_ec_all.yaml
    ec_idle: $PWD/../ecat_config/hal/awesome_leg_ec_all.yaml

# threads
xbotcore_threads:
    rt_main:  {sched: fifo , prio: 60, period: 0.001, core_id: 2}
    rt_main_slow:  {sched: fifo , prio: 60, period: 0.02, core_id: 1}
    nrt_main: {sched: other, prio: 0 , period: 0.005}
    rt_main_fast:  {sched: fifo , prio: 60, period: 0.001, core_id: 2}


# plugins
xbotcore_plugins:

    homing:
        thread: rt_main
        type: homing_example

    ros_io: {thread: nrt_main, type: ros_io}

    ros_control: {thread: nrt_main, type: ros_control}
    
    ec_ros: {thread: nrt_main, type: ec_ros}

    base_est_rt:
        thread: rt_main_slow
        type: base_est_rt
        params:

            urdf_path_base_est: {value: $PWD/../../description/urdf/generated/awesome_leg.urdf, type: file} # used by the model interface
            srdf_path_base_est: {value: $PWD/../../description/srdf/awesome_leg_test_rig.srdf, type: file}

            ik_problem_path: {value: $PWD/../cartesio/energy_recovery/awesome_leg_base_estimation.yaml, type: yamlfile}

            mat_path: {value: /tmp/, type: string}
            dump_mat_suffix: {value: "base_est_rt", type: string}
            matlogger_buffer_size: {value: 1e5, type: double}

            tip_link_name: {value: "tip1", type: string}
            base_link_name: {value: "base_link", type: string}
            test_rig_linkname: {value: "test_rig", type: string}
            tip_fts_name: {value: "tip1_fts", type: string}
            contact_linkname: {value: "tip1", type: string}

            contact_release_thr: {value: 30.0, type: double}
            contact_attach_thr: {value: 90.0, type: double}

            contact_detection_gz_truth: {value: 10.0, type: double}

            mov_avrg_cutoff_freq: {value: 15.0, type: double}
            mov_avrg_cutoff_freq_tau_c: {value: 15.0, type: double}

            obs_bw: {value: 15.0, type: double}

            svd_thresh: {value: 0.1, type: double}

            use_gz_truth: {value: "false", type: bool}


    jmp_replayer_rt:
        thread: rt_main_fast
        type: jmp_replayer_rt
        params:

            mat_path: {value: /tmp/jump_generation_15-11-2022-17_04_43/, type: string}
            mat_name: {value: apex_awesome_jump_ref.mat, type: string}
            dump_mat_suffix: {value: traj_replay, type: string}
            matlogger_buffer_size: {value: 1e5, type: double}

            is_first_jnt_passive : {value: true, type: bool}
            resample: {value: true, type: bool}

            replay_stiffness: {value: [4000.0, 4000.0], type: Eigen::VectorXd}
            replay_damping: {value: [50.0, 50.0], type: Eigen::VectorXd}
            touchdown_stiffness: {value: [35.0, 20.0], type: Eigen::VectorXd}
            touchdown_damping: {value: [6.0, 6.0], type: Eigen::VectorXd}
#            touchdown_stiffness: {value: [15.0, 10.0], type: Eigen::VectorXd}
#            touchdown_damping: {value: [3.0, 3.0], type: Eigen::VectorXd}
#            touchdown_stiffness: {value: [4000.0, 4000.0], type: Eigen::VectorXd}
#            touchdown_damping: {value: [100.0, 100.0], type: Eigen::VectorXd}
            stop_stiffness: {value: [200.0, 200.0], type: Eigen::VectorXd}
            stop_damping: {value: [8.0, 8.0], type: Eigen::VectorXd}

            send_pos_ref: {value: true, type: bool}
            send_vel_ref: {value: true, type: bool}
            send_eff_ref: {value: false, type: bool}

            approach_traj_exec_time: {value: 5.0, type: double}
            imp_ramp_time: {value: 5.0, type: double}

            reduce_dumped_sol_size: {value: false, type: bool}

            send_whole_traj: {value: true, type: bool}

            verbose: {value: false, type: bool}

            resample_err_tolerance: {value: 1e-2, type: double}

# global parameters
xbotcore_param:
    /jm/tx_filter_autostart: {value: true, type: bool}
    /jm/tx_filter_cutoff: {value: 2.0, type: double}
    
