# xbot_initial_pos_pub.py configuration file

xbot_initial_pos_pub: 

  urdf_path: $(find awesome_leg)/description/urdf/awesome_leg.urdf

  approaching_traj: # configurations for the node used to move the leg to its initial position

        n_intervals: 200 # number of intervals of the generated trajectory
        T_execution: 6.0 # desired execution time 
        standby_time: 0.0 # time delay at the end of the approach maneouver
        q_p_target: [-1.5, 0.5] # target joint positions
        
        ctrl_mode: [25, 25]
        stiffness: [500, 500]
        damping:  [5, 5]
