xbotcore_devices:

    joint_ec:
        names: []
        thread: rt_main
        params:
            robot_name: &rn {value: NoNe, type: string}
            ignore_id: {value: [66], type: vector<int>}
            config_ec_pos: 
                value: $PWD/../joint_config/awesome_leg_pos3b.yaml
                type: yamlfile
            config_ec_imp: 
                value: $PWD/../joint_config/awesome_leg_impd4.yaml
                type: yamlfile
            config_ec_idle: 
                value: $PWD/../joint_config/awesome_leg_idle.yaml
                type: yamlfile
            joint_id_map: &jim
                value: $PWD/../joint_map/awesome_leg_joint_map.yaml
                type: yamlfile


    joint_master:
        master: true
        thread: rt_main


    aw_leg_pow_ec:
        names: []
        thread: rt_main
        params:
            names: {value: [power_sensor], type: vector<string>}
            joint_id_map: *jim
