# Tip CARTESIAN impedance control using CartesIO Acceleration Support "Interaction" extension

solver_options:
    regularization: 1e-14
    back_end: "qpoases"

stack: # tasks
    - ["tip"]

constraints: ["JointLimits", "VelocityLimits"]

tip:
  lib_name: libcartesio_acceleration_support.so
  type: "Interaction" # Interaction wraps Cartesian and adds functionalities to allow cartesian impedance control
  lambda: 1 # if using "Interaction", this is simply a scaling factor
  stiffness: [1000, 0, 1000, 0, 10, 0]
  damping: [100, 0, 100, 0, 1, 0]
  distal_link: "tip"
  indices: [0, 1, 2, 3, 4, 5] 

JointLimits:
  lib_name: libcartesio_acceleration_support.so
  type: "JointLimits"
  bound_scaling: 1

VelocityLimits:
  lib_name: libcartesio_acceleration_support.so
  type: "VelocityLimits"
  bound_scaling: 1
       
