solver_options:
    regularization: 1e-3
    back_end: "qpoases"

stack: # tasks
    - ["tip"]

constraints: ["Dynamics", "JointLimits", "VelocityLimits"]

tip:
  lib_name: libcartesio_acceleration_support.so
  type: "Cartesian"
  lambda: 0.1
  distal_link: "tip"

JointLimits:
  lib_name: libcartesio_acceleration_support.so
  type: "JointLimits"
  bound_scaling: 1.0

VelocityLimits:
  lib_name: libcartesio_acceleration_support.so
  type: "VelocityLimits"
  bound_scaling: 1.0
       
