solver_options:
    regularization: 1e-3
    back_end: "qpoases"

stack: # tasks
    - ["tip"]

constraints: ["JointLimits", "VelocityLimits"]

tip:
  type: "Cartesian"
  lambda: 1
  distal_link: "tip"

JointLimits:
  type: "JointLimits"
  bound_scaling: 1.0

VelocityLimits:
  type: "VelocityLimits"
  bound_scaling: 1.0
       
