# USED FOR SETTINGS SOME SOLVER OPTIONS
horizon:

  urdf_relative_path: "/description/urdf/awesome_leg_complete_sliding_all.urdf" # urdf relative path (wrt to the package)
 
  media_relative_path: "/media/horizon_trot/sliding_all" # relative path where graphs, etc.. are saved

  opt_results_rel_path: "/opt_results/horizon_trot/sliding_all"

  joint_cntrl:

    hip_joint:

      control_mode: "position" # "position", "velocity", "effort"
      stiffness: 250.0
      damping: 5.0

    knee_joint:

      control_mode: "position"
      stiffness: 250.0
      damping: 5.0

  horizon_solver:

    save_sol_as_init: false # if true, the solution is also saved as a candidate for future optimization initializations

    employ_opt_init: false # whether to use the initial guess or not
    
    variable_dt:

      problem_settings:

        n_nodes: 100
        n_takeoff: 50
        dt: 0.01

        forward_vel: 1

        tip_ground_clearance: 0.1

        dt_lb: 0.01
        dt_ub: 0.1
 
        solver:
          name: "ipopt"
          tolerance: 0.0001
          max_iter: 1000
          linear_solver_name: "ma57"    

        test_rig:
          lb: -0.4
          ub:  0.4      

        cost_weights:
          contact_force: 0.001
          weight_fictitious_actuation: 10.0
          small_q_p_ddot: 0.001
          weight_hip_i_d: 1.0
          weight_knee_i_d: 1.0
          weight_forward_vel: 1.0
          
