horizon_solver:

  is_adaptive_dt: true 
  
  save_sol_as_init: false # if 1, the solution is also saved as a candidate for future optimization initializations

  employ_opt_init: false # whether to use the initial guess or not

  constant_dt:

   problem_settings:

     T_f_horizon: 5.0
     T_takeoff_horizon: 3.0
     T_touchdown_horizon: 3.3
     dt: 0.08  

     solver:
       name: "ipopt"
       tolerance: 0.0001
       max_iter: 1000
       linear_solver_name: "ma57"  

     test_rig:
       lb: -0.4
       ub:  0.4  

    #  hip:
    #    lb: 
    #    ub:  

    #  knee:
    #    lb: 
    #    ub: 

     initial_conditions:
       q_p:     [0.0, 0.0, 0.0]
       q_p_dot: [0.0, 0.0, 0.0]

     cost_weights:
       contact_force: 0.01
       terminal_postural: 1000
       small_q_p_ddot: 1
       big_hip_jump: 10
       big_foot_tip_clearance: 0.00001

  variable_dt: 

    problem_settings:   
     
     is_single_dt: true
     n_nodes: 100 # number of intervals (total nodes are n_nodes+1)
     n_pre_takeoff: 60
     n_takeoff: 60
     n_touchdown: 80
     n_post_touchdown: 80 
     dt_lb: 0.01
     dt_ub: 0.1

     solver:

       name: "ipopt"
       tolerance: 0.0001
       max_iter: 1000
       linear_solver_name: "ma57"    

     test_rig:

       lb: -0.4
       ub:  0.4      

    #  hip:
    #    lb: 
    #    ub:       

    #  knee:
    #    lb: 
    #    ub: 

     initial_conditions:

       q_p:     [0.0, 0.0, 0.0]
       q_p_dot: [0.0, 0.0, 0.0]

     cost_weights:
     
       contact_force: 0.01
       terminal_postural: 100
       small_q_p_ddot: 1
       big_hip_jump: 0.00001
       big_foot_tip_clearance: 100000000
   



