# YAML config file associated with inertial_identification_dynamic.py (still to be developed) script.

inertial_identification_dynamic:

  urdf_path: $(find awesome_leg)/description/urdf/generated/awesome_leg_reduced.urdf

  matfile_path: $(find awesome_leg)/test_results/fixed_hip_setup/cyclic_tests/large_excursion/fast/robot_state_log__0_2022_01_26__16_49_17.mat
