# robot_state_log_plotter.py config file

robot_state_log_plotter:

  # matfile_path: $(find awesome_leg)/$(find awesome_leg)//fixed_hip_setup/tip_cart_acc_cntrl/checks/real_tests/1_04_22/robot_state_log1.mat # logged data mat file path
  matfile_path: /tmp/centauro_robot_state_log.mat

  save_fig: false # whether or not to save figures to the destination folder (defaults to true if show_plots is false)
  
  save_fig_path: /tmp