# robot_state_log_plotter.py config file

robot_state_log_plotter:

  actuators_config_path: $(find awesome_leg_pholus)/config/actuators.yaml

  urdf_path: $(find awesome_leg_pholus)/description/urdf/awesome_leg_reduced_calibrated.urdf # urdf relative path (wrt to the package)
  srdf_path: $(find awesome_leg_pholus)/description/srdf/awesome_leg_reduced.srdf # srdf relative path (wrt to the package)
  
  # matfile_path: $(find awesome_leg_pholus)/test_results/fixed_hip_setup/tip_cart_acc_cntrl/checks/real_tests/1_04_22/robot_state_log1.mat # logged data mat file path
  matfile_path: /home/andreap/hhcm_ws/src/awesome_leg_pholus/test_results/fixed_hip_setup/DSP_bypass/DSP/fast_filter/stiffness_fromGUI/robot_state_log__0_2022_04_07__16_38_34.mat
  # matfile_path: /home/andreap/hhcm_ws/src/awesome_leg_pholus/test_results/fixed_hip_setup/DSP_bypass/noDSP/0_001_dt/robot_state_log__0_2022_04_07__15_36_46.mat

  save_fig: false # whether or not to save figures to the destination folder (defaults to true if show_plots is false)
  
  save_fig_path: /tmp