# Tip CARTESIAN impedance control using CartesIO Acceleration Support Interaction extension

solver_options:
    regularization: 0.0
    back_end: qpoases
    # back_end: osqp
    front_end: nhqp
    nhqp_min_sv_ratio: 0.1

stack: # tasks
    - [tip]

constraints: [] #[JointLimits, VelocityLimits] # more robust without this constraints

tip:
  lib_name: libcartesio_acceleration_support.so
  type: Interaction # Interaction wraps Cartesian and adds functionalities to allow cartesian impedance control
  lambda: 1 # if using Interaction, this is simply a scaling factor
  stiffness: [200, 0, 200, 0, 0, 0]
  damping: [50, 0, 50, 0, 0, 0]
  distal_link: tip
  indices: [0, 2] 

JointLimits:
  lib_name: libcartesio_acceleration_support.so
  type: JointLimits
  bound_scaling: 1

VelocityLimits:
  lib_name: libcartesio_acceleration_support.so
  type: VelocityLimits
  bound_scaling: 1