#******************** TOUCHDOWN OPTIMIZATION ********************#

energy_recov_opt:

  i_q_estimation:

    tanh_coeff: 50 # used by the continous iq estimation model

  problem:

    # n_int: 100

    # dt_lb: 0.001
    # dt_ub: 0.05

    # n_int: 100

    # dt_lb: 0.001
    # dt_ub: 0.05

    n_int: 100

    dt_lb: 0.05
    dt_ub: 0.05

    is_iq_cnstrnt: false # whether to use the iq constraint or not
    is_friction_cone: false # whether to use a friction constraint or not

    friction_cnstrnt:
      mu_friction_cone: 0.6

    landing_vel: -1.0

    is_q_ig: True

    q_ig: [1.0, 1.0]

    use_soft_imp_cntrl: False

    breaking_perc: 0.1 # [0, 1] % from the final node over which the average joint velocity is contrainted to be low
    q_dot_breaking_thresh: 0.01
    use_braking_constraint: False

    weights:

      weight_f_contact: -1 # cost for penalizing contact forces
      weight_f_contact_diff: -1 #0.1 # cost for penalizing differences between successive f_contacts
      weight_jnt_input: -1 # cost for penalizing joint accelerations (which are the input)
      weight_jnt_input_diff: -1 #0.05 # cost for penalizing differences between successive inputs
      weight_q_dot: -1 
      weight_q_dot_diff: -1

      weight_reg_energy: -1
      weight_impact_min: 1

      weight_q_reg: -1

      weight_braking: -1

      weight_imp_cntrl: -1

  solver:

    ipopt_tol: 0.000001
    ipopt_maxiter: 10000
    ipopt_cnstr_viol_tol: 0.000001 # 1e-6 is a reasonable value for accurate results
    name: "ipopt"

  transcription:
    name: "multiple_shooting"
    integrator_name: "RK4"