#******************** TOUCHDOWN OPTIMIZATION ********************#

energy_recov_opt:

  i_q_estimation:

    tanh_coeff: 20 # used by the continous iq estimation model

  problem:

    n_int: 2

    dt_lb: 0.0001
    dt_ub: 1
    
    is_iq_cnstrnt: true # whether to use the iq constraint or not
    is_friction_cone: true # whether to use a friction constraint or not

    friction_cnstrnt:
      mu_friction_cone: 0.6

    landing_vel: -1.0

    weights:

      weight_f_contact: 0.0001 # cost for penalizing contact forces
      weight_f_contact_diff: -1 #0.1 # cost for penalizing differences between successive f_contacts
      weight_jnt_input: 0.0001 # cost for penalizing joint accelerations (which are the input)
      weight_jnt_input_diff: -1 #0.05 # cost for penalizing differences between successive inputs
      weight_q_dot: -1 #0.1
      weight_q_dot_diff: -1

      weight_reg_energy: -1
      weight_impact_min: 20000000

  solver:

    ipopt_tol: 0.000001
    ipopt_maxiter: 10000
    ipopt_cnstr_viol_tol: 0.000001 # 1e-6 is a reasonable value for accurate results
    name: "ipopt"

  transcription:
    name: "multiple_shooting"
    integrator_name: "RK4"