<?xml version="1.0" encoding="utf-8" ?>

<robot name="awesome_leg" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find awesome_leg)/description/urdf/awesome_leg.gazebo.xacro" />

    <xacro:macro name="awesome_leg" params="id base_link add_ft_sensor" >

        <xacro:awesome_leg_gazebo id="${id}" add_ft_sensor="${add_ft_sensor}"/> 

        <xacro:unless value="${ base_link=='None' or base_link=='none'}">
            <!-- only add joint to base if argument is non-empty -->
            <joint name="hip_pitch_${id}" type="revolute">
                <parent link="${base_link}" />
                <child link="femur${id}" />
                <axis xyz="0 1 0"/>
                <origin xyz="0 ${214.6 * mmTom} 0" />
                <limit effort="112" lower="-2.4" upper="2.4" velocity="20.0"/>
            </joint>

        </xacro:unless>

        <link name="femur${id}">
            <inertial>
                <origin rpy="${89.6977809 * DEG2RAD} ${-80.3474629 * DEG2RAD} ${-89.9195968 * DEG2RAD}" xyz="${-1.7807105e-02 * mmTom} ${-3.4271947e+01 * mmTom} ${-2.2282064e+02 * mmTom}"/>
                <mass value="3.3712777"/>
                <inertia ixx="${4.6647423e+04 * kgmm2_2_kgm2}" iyy="${4.3720135e+04 * kgmm2_2_kgm2}" izz="${7.5794813e+04 * kgmm2_2_kgm2}"
                    ixy="${-1.2697640e+01 * kgmm2_2_kgm2}" ixz="${-3.2745810e+01 * kgmm2_2_kgm2}" iyz="${-6.3299091e+04 * kgmm2_2_kgm2}" />
            </inertial>
            <visual>
                <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://awesome_leg/description/new_meshes/visual/femur.stl" scale="${dmTom} ${dmTom} ${dmTom}"/>
                </geometry>
                <material name="darkblue"/>
            </visual>
            <collision>
                <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://awesome_leg/description/new_meshes/collision/femur.stl" scale="${dmTom} ${dmTom} ${dmTom}"/>
                </geometry>
            </collision>
        </link>

        <joint name="knee_pitch_${id}" type="revolute">
            <parent link="femur${id}"/>
            <child link="shin${id}"/>
            <origin rpy="0.0 0.0 0.0" xyz="0.0 ${-118.2 * mmTom} ${-300.0 * mmTom}"/>
            <axis xyz="0 -1 0"/>
            <limit effort="112" lower="-2.4" upper="2.4" velocity="20.0"/>
        </joint>

        <link name="shin${id}">
            <inertial>
                <origin rpy="${-87.960 * DEG2RAD} ${0.0 * DEG2RAD} ${-90 * DEG2RAD}" xyz="${9.2284672e-04 * mmTom} ${1.759883e+01 * mmTom} ${-1.8730054e+02 * mmTom}"/>
                <mass value="1.3106594"/>
                <inertia ixx="${4.0133965e+04 * kgmm2_2_kgm2}" iyy="${4.0269285e+04 * kgmm2_2_kgm2}" izz="${1.5274496e+03 * kgmm2_2_kgm2}"
                    ixy="${4.6219082e-02 * kgmm2_2_kgm2}" ixz="${-3.0432320e-01 * kgmm2_2_kgm2}" iyz="${1.3816329e+03 * kgmm2_2_kgm2}" />
            </inertial>
            <visual>
                <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
                <geometry>
                    <mesh filename="package://awesome_leg/description/new_meshes/visual/shin.stl" scale="${dmTom} ${dmTom} ${dmTom}"/>
                </geometry>
                <material name="grey"/>
            </visual>

            <xacro:unless value="${ add_ft_sensor == True}">
                <collision>
                    <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.0"/>
                    <geometry>
                        <mesh filename="package://awesome_leg/description/new_meshes/collision/shin.stl" scale="${dmTom} ${dmTom} ${dmTom}"/>
                    </geometry>
                </collision>
            </xacro:unless>

        </link>

        <xacro:unless value="${ add_ft_sensor == True}">

            <joint name="tip_joint_${id}" type="fixed">
                <parent link="shin${id}"/>
                <child link="tip${id}"/>
                <origin xyz="0.0 ${23.3000 * mmTom} ${-451 * mmTom}"/>
            </joint>

            <link name="tip${id}"/>
            
        </xacro:unless>

        <xacro:if value="${ add_ft_sensor == True}"> 

            <joint name="tip_joint_${id}" type="prismatic">
                <parent link="shin${id}"/>
                <child link="tip${id}"/>
                <origin xyz="0.0 ${23.3000 * mmTom} ${-451 * mmTom}"/>
                <limit effort="0" lower="0.0" upper="0.0" velocity="0.0"/>
                <axis  xyz="0 0 1"/>
            </joint>
            <link name="tip${id}">
                    <origin xyz="0.0 0.0 0.0"/>
                    <inertial>  
                        <origin xyz="0.0 0.0 0.0"/>
                        <mass value="${aux_mass_tip}"/> <!-- fake inertial value, otherwise Gazebo throws errors  -->
                        <inertia ixx="0" iyy="0" izz="0"
                            ixy="0" ixz="0" iyz="0" />
                    </inertial>
                    <collision>
                        <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 ${fts_sphere_radius - fts_delta}"/>
                        <geometry>
                            <sphere radius="${fts_sphere_radius}"/>
                        </geometry> 
                        <max_contacts> 1 </max_contacts>
                        <!-- <surface>
                            <contact>
                                <ode>
                                    <kp>1000000000</kp>
                                    <kd>1</kd>
                                    <min_depth> 0 </min_depth>
                                    <max_vel>0.01</max_vel>-
                                    <soft_cfm> 0.01 </soft_cfm>
                                    <soft_erp> 0.2 </soft_erp>
                                </ode>
                            </contact>
                            <friction>
                                <ode>
                                <mu>1</mu>
                                <mu2>1</mu2>
                                </ode>
                            </friction>
                        </surface> -->
                    </collision>

                    
            </link>

        </xacro:if>

    </xacro:macro>

</robot>
